#findSharedExpressedGenePairs.R


library(argparse)
parser=ArgumentParser()
parser$add_argument("-r1", "--firstDataset", help="input bed file generated by bedtools window")
parser$add_argument("-r2", "--secondDataset", help="output bed file name")
parser$add_argument("-o", "--outputFile", help="output file name with list of conserved gene pairs")
args=parser$parse_args()
cat('Finding which gene pairs have >= 100 fold change in the first dataset and the second dataset.',"\n")

#read foldChange gene pair files generated from appendFPKM.R
rnaDataset1 <- read.table(args$firstDataset, header=T, sep="\t")
rnaDataset2 <- read.table(args$secondDataset, header=T, sep="\t")

#make pair_ids for each gene pair
rnaDataset1$pair_id <- paste(rnaDataset1$tracking_id1, rnaDataset1$tracking_id2, sep="")
rnaDataset2$pair_id <- paste(rnaDataset2$tracking_id1, rnaDataset2$tracking_id2, sep="")

#only take pairs with fold change >= 100
rnaDataset1.100foldChange <- subset(rnaDataset1, foldChange >= 100)
rnaDataset2.100foldChange <- subset(rnaDataset2, foldChange >= 100)

#only take gene pairs that show 100 fold change in each dataset
rnaDataset1.shared100fc <- subset(rnaDataset1.100foldChange, pair_id %in% rnaDataset2.100foldChange$pair_id)

write.table(rnaDataset1.shared100fc, file=args$outputFile, row.names=F, col.names=T, sep="\t", quote=F)