#############################
# Author: Lynsey Kovar
# findSharedExpressedGenePairs.R
# Takes two input files generated from appendFPKM.R and checks to see if there are shared gene pairs between them. Output is list of gene pairs from first file that also meet criteria in second file. 
#############################

library(argparse)
parser=ArgumentParser()
parser$add_argument("-r1", "--firstDataset", help="first gene pair list generated by appendFPKM.R")
parser$add_argument("-r2", "--secondDataset", help="second gene pair list generated by appendFPKM.R")
parser$add_argument("-o", "--outputFile", help="output file name for gene pairs in both datasets")
parser$add_argument("-f", "--foldChange", help="desired minimum fold change")
args=parser$parse_args()
cat('Finding which gene pairs have >= ', args$foldChange, ' fold change in the first dataset and the second dataset.',"\n")

#read foldChange gene pair files generated from appendFPKM.R
rnaDataset1 <- read.table(args$firstDataset, header=T, sep="\t")
rnaDataset2 <- read.table(args$secondDataset, header=T, sep="\t")

#make pair_ids for each gene pair
rnaDataset1$pair_id <- paste(rnaDataset1$tracking_id1, rnaDataset1$tracking_id2, sep="")
rnaDataset2$pair_id <- paste(rnaDataset2$tracking_id1, rnaDataset2$tracking_id2, sep="")

#only take pairs with fold change >= -f argument
rnaDataset1.foldChange <- subset(rnaDataset1, foldChange >= as.numeric(args$foldChange))
rnaDataset2.foldChange <- subset(rnaDataset2, foldChange >= as.numeric(args$foldChange))

#only take gene pairs that show 100 fold change in each dataset
rnaDataset1.foldChange.shared <- subset(rnaDataset1.foldChange, pair_id %in% rnaDataset2.foldChange$pair_id)

write.table(rnaDataset1.foldChange.shared, file=args$outputFile, row.names=F, col.names=T, sep="\t", quote=F)