#getDiffExpressedNeighbors.R

library(argparse)
parser=ArgumentParser()
parser$add_argument("-i", "--inputFile", help="input bed file generated by bedtools window")
parser$add_argument("-o", "--outputFile", help="output bed file name")
args=parser$parse_args()
cat('Extracting adjacent genes with high fold difference in expression.',"\n")

windowBed <- read.table(args$inputFile, header=F, sep="\t")
names(windowBed) <- c("chr1", "start1", "stop1", "strand1", "fpkm1", "chr2", "start2", "stop2", "strand2", "fpkm2")

windowBed <- subset(windowBed, start1 != start2)
windowBed$minVal <- apply(windowBed[,c(2,3,7,8)], 1, FUN=min)
windowBed$maxVal <- apply(windowBed[,c(2,3,7,8)], 1, FUN=max)

windowBed$minMax <- paste(windowBed$chr1, windowBed$minVal, windowBed$maxVal,sep="")

windowBed.unique <- subset(windowBed, !duplicated(minMax))
windowBed.unique$minVal <- NULL
windowBed.unique$maxVal <- NULL
windowBed.unique$minMax <- NULL

windowBed.unique$minFPKM <- apply(windowBed.unique[,c(5,10)], 1, FUN=min)
windowBed.unique$maxFPKM <- apply(windowBed.unique[,c(5,10)], 1, FUN=max)

windowBed.unique$foldChange <- ifelse(windowBed.unique$minFPKM == 0, windowBed.unique$maxFPKM, abs((windowBed.unique$minFPKM - windowBed.unique$maxFPKM)/windowBed.unique$minFPKM))
windowBed.unique <- subset(windowBed.unique, maxFPKM >= 1 & minFPKM >=1)

cat("there are ", nrow(windowBed.unique), " pairs of differentially expressed genes.\n")

png(paste(args$outputFile, "boxplot.png",sep=""))
boxplot(windowBed.unique$foldChange, main=paste(args$outputFile, " fold change distribution"))
dev.off()

write.table(windowBed.unique, args$outputFile, row.names=F, col.names=T, quote=F, sep="\t")