#getGenePairs.R

library(argparse)
library(dplyr)
library(tidyr)
parser=ArgumentParser()
parser$add_argument("-i", "--inputFile", help="input genes.fpkm_tracking file generated by cufflinks")
parser$add_argument("-o", "--outputFile", help="output bed file name")
args=parser$parse_args()
cat('Generating bedfile with expression values.',"\n")

fpkmTracking <- read.table(args$inputFile, header=T, sep="\t")
fpkmTracking <- fpkmTracking %>% separate(locus, c("chr", "interval"), ":")
fpkmTracking <- fpkmTracking %>% separate(interval, c("start", "stop"), "-")

fpkmTracking$strand <- ifelse(fpkmTracking$start > fpkmTracking$stop, "-", "+")
bedFile <- data.frame(chr=fpkmTracking$chr, start=fpkmTracking$start, stop=fpkmTracking$stop, strand=fpkmTracking$strand, fpkm=fpkmTracking$FPKM)

write.table(bedFile, args$outputFile, col.names=F, row.names=F, quote=F, sep="\t")