#############################
# Author: Lynsey Kovar
# getGenePairsSharedInGenomes.R
# Takes map file between genomes and combined fpkm_tracking text file for gene pairs generated by findSharedExpressedGenePairs.R 
#############################


library(argparse)
parser=ArgumentParser()
parser$add_argument("-d", "--dbFile", help="findSharedExpressedGenePairs.R output file for data mapped using db genome used to create mapfile")
parser$add_argument("-q", "--queryFile", help="findSharedExpressedGenePairs.R output file for data mapped using query genome used to create mapfile")
parser$add_argument("-m", "--mapFile", help="map file name, should contain columns dbGeneName and queryGeneName")
parser$add_argument("-o", "--outputSuffix", help="output file prefix")
args=parser$parse_args()
cat("finding gene pairs shared between ", args$dbFile, " and ", args$queryFile, "\n")

#prevent conversion of pairId to scientific notation
options(scipen=999)

dbFile <- read.table(args$dbFile, header=T, sep="\t")
queryFile <- read.table(args$queryFile, header=T, sep="\t")
mapFile <- read.table(args$mapFile, header=T, sep="\t")

dbFile$pair_id <- paste(dbFile$tracking_id1, dbFile$tracking_id2, sep="")
queryFile$pair_id <- paste(queryFile$tracking_id1, queryFile$tracking_id2, sep="")

#make tracking_id1-otherGenome and tracking_id2-otherGenome columns using merge function in db and query files

#dbFile
dbFile <- merge(dbFile, mapFile, by.x="tracking_id1", by.y="dbGeneName")
colnames(dbFile)[names(dbFile) == "queryGeneName"] <- "tracking_id1.otherGenome"

dbFile <- merge(dbFile, mapFile, by.x="tracking_id2", by.y="dbGeneName")
colnames(dbFile)[names(dbFile) == "queryGeneName"] <- "tracking_id2.otherGenome"

#queryFile
queryFile <- merge(queryFile, mapFile, by.x="tracking_id1", by.y="queryGeneName")
names(queryFile)[names(queryFile) == "dbGeneName"] <- "tracking_id1.otherGenome"

queryFile <- merge(queryFile, mapFile, by.x="tracking_id2", by.y="queryGeneName")
names(queryFile)[names(queryFile) == "dbGeneName"] <- "tracking_id2.otherGenome"

#make pair_id2 column for each file
dbFile$pair_id2 <- paste(dbFile$tracking_id1.otherGenome, dbFile$tracking_id2.otherGenome, sep="")
queryFile$pair_id2 <- paste(queryFile$tracking_id1.otherGenome, queryFile$tracking_id2.otherGenome, sep="")

#find matching gene pairs across genomes
dbFile <- subset(dbFile, pair_id %in% queryFile$pair_id2)
queryFile <- subset(queryFile, pair_id %in% dbFile$pair_id2)

#write output
write.table(dbFile, paste(args$dbFile, args$outputSuffix, sep="."), row.names=F, col.names=T, sep="\t", quote=F)
write.table(queryFile, paste(args$queryFile, args$outputSuffix, sep="."), row.names=F, col.names=T, sep="\t", quote=F)


